name: CoUMapFiller
version: 1.0.4
author: CoU Development Team
description: 'A map entity builder for the online game: Children of Ur'
homepage: childrenofur.com
dependencies:
  browser: any
  libld:
    git:
      ref: master
      url: https://github.com/ChildrenOfUr/libld
  nomirrorsmap: "^1.0.24"

transformers:
  - nomirrorsmap