name: CoUMapFiller
version: 0.0.1
author: CoU Development Team
description: 'A map entity builder for the online game: Children of Ur'
homepage: childrenofur.com
dependencies:
  browser: any
  libld:
    path: ../libld
